"""empty message

Revision ID: 5286e66391f1
Revises: 
Create Date: 2023-10-08 22:23:07.334923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5286e66391f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('payment', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('orders_products',
    sa.Column('order_product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('order_product_id', 'product_id', 'order_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('type')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('payed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('payments')
    op.drop_table('orders_products')
    op.drop_table('orders')
    op.drop_table('clients')
    # ### end Alembic commands ###
