apiVersion: v1
kind: Service
metadata:
  name: svcfiaptechchallenge
spec:
  type: NodePort
  ports:
    - port: 80      
      targetPort: 5000
      nodePort: 32000
  selector:
    app: fiaptechchallenge