apiVersion: v1
kind: Service
metadata:
  name: svcfiaptechchallenge
  namespace: "default"
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: fiaptechchallenge
