apiVersion: v1
kind: Service
metadata:
  name: svcfiaptechchallenge
  namespace: "default"
  labels:
    app: flask-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: fiaptechchallenge
  type: LoadBalancer
  loadBalancerIP: ""