apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiaptechchallenge
spec:
  selector:
    matchLabels:
      app: fiaptechchallenge
  replicas: 1
  template:
    metadata:
      labels:
        app: fiaptechchallenge
    spec:
      containers:
      - name: fiaptechchallenge
        image: DOCKER_IMAGE
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        startupProbe:
          httpGet:
            path: /ping
            port: 5000
          failureThreshold: 3
          periodSeconds: 30
        env:
          - name: POSTGRES_DB
            value: VAL_POSTGRES_DB_NAME
          - name: POSTGRES_USER
            value: VAL_POSTGRES_DB_USER
          - name: POSTGRES_PASSWORD
            value: VAL_POSTGRES_DB_PASSWORD
          - name: POSTGRES_SERVICE_HOST
            value: VAL_POSTGRES_DB_HOST
