apiVersion: v1
kind: Service
metadata:
  name: svcfiaptechchallenge
  namespace: "default"
  labels:
    app: flask-app
spec:
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30100
  selector:
    app: fiaptechchallenge
  type: NodePort
